name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true 
        type: boolean
jobs:
  deploy:
    strategy:
      matrix:
        organization: ['apple', 'banana', 'peach', 'apple-um']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Set env values
        run: cat envs/production/.env.${{ matrix.organization }} > .env.production
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          mode: production
      - name: Build Project
        run: yarn build
        env:
          CI: true
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist --message "${{ github.sha }}"
        env:
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
